### ISSUE TITLE
Checksum error for download_CelebA.py

### ISSUE THREAD

**Issue by SuwoongHeo** [suvojit-0x55aa/celebA-HQ-dataset-download#9]
Hi, I have tried to download the celebA using your code and I got the following errors as below. It seems that the checksum of `img_celeba.7z.001` does not match. Is there any workaround for this? Thanks!
```
(celebaHQ) swheo@insight56:/ssd2/swheo/db/celebA-HQ-dataset-download$ sh ./create_celebA-HQ.sh ./celebA-HQ   
/ssd2/swheo/db/celebA-HQ-dataset-download
Downloading Anno/list_landmarks_celeba.txt to ./celebA-HQ/celebA/Anno/list_landmarks_celeba.txt
...
Check SHA1 ./celebA-HQ/celebA/img_celeba.7z.001
Traceback (most recent call last):
  File "/ssd2/swheo/db/celebA-HQ-dataset-download/download_celebA.py", line 186, in <module>
    download_celabA(dataset_dir)
  File "/ssd2/swheo/db/celebA-HQ-dataset-download/download_celebA.py", line 178, in download_celabA
    download_and_check(_IMGS_DRIVE, dataset_dir)
  File "/ssd2/swheo/db/celebA-HQ-dataset-download/download_celebA.py", line 112, in download_and_check
    raise RuntimeError('Checksum mismatch for %s.' % save_path)
RuntimeError: Checksum mismatch for ./celebA-HQ/celebA/img_celeba.7z.001.
...
Deal with file: image_list.txt
./celebA-HQ/celebA-HQ/image_list.txt: 23.0B [00:00, 306B/s]

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,72 CPUs Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (50654),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2257 bytes (3 KiB)   

Extracting archive: ./celebA-HQ/celebA/img_celeba.7z
ERROR: ./celebA-HQ/celebA/img_celeba.7z
./celebA-HQ/celebA/img_celeba.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
  File "/ssd2/swheo/db/celebA-HQ-dataset-download/create_celeba_HQ.py", line 71
    print '\n\nWorker thread caught an exception:\n' + result.traceback + '\n',
    
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by suvojit-0x55aa** [comment]
I'll have to check if the hosted data is still working. Meanwhile if you need the images urgently, you can use: https://github.com/suvojit-0x55aa/celebA-HQ-dataset-download#pre-calculated-dataset

**Comment by SuwoongHeo** [comment]
I downloaded data from the link. Thank you!
